Farmucho/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace Farmucho.Models
{
    public class Cliente
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Nombre { get; set; }
        [Required]
        public string? Apellido { get; set; }
        public int Telefono { get; set; }
        public string? Mail { get; set; }
        public int Cuit { get; set; }
    }
}

Farmucho/Controllers/ClienteController.cs
using Farmucho.Models;
using Microsoft.AspNetCore.Mvc;

namespace Farmucho.Controllers
{
    public class ClienteController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(Lista.ListarClientes());
        }
        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GuardarAgregar(Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                using (FarmaciaContext context = new())
                {
                    context.Clientes?.Add(cliente);
                    context.SaveChanges();
                    TempData["msg"] = "<script>alert('El cliente fue agregado con éxito');</script>";
                }
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "<script>alert('Por favor, llene todos los campos');</script>";
                return View("Agregar");
            }
        }
        [HttpGet]
        public IActionResult Editar(int id)
        {
            using (FarmaciaContext context = new())
            {
                Cliente? cliente = context.Clientes?.Find(id);

                if (cliente != null)
                {
                    return View(cliente);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
        }
        [HttpPost]
        public IActionResult Update(int id, Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                using (FarmaciaContext context = new())
                {
                    if (id != cliente.Id)
                    {
                        return NotFound();
                    }
                    else
                    {
                        context.Clientes?.Update(cliente);
                        context.SaveChanges();
                        TempData["msg"] = "<script>alert('El cliente fue editado con éxito');</script>";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "<script>alert('Por favor, llene todos los campos');</script>";
                return View("Editar");
            }
        }
        [HttpGet]
        public IActionResult Borrar(int id)
        {
            using (FarmaciaContext context = new())
            {
                if (id != 0)
                {
                    Cliente? cliente = context.Clientes?.Find(id);
                    if (cliente != null)
                    {
                        context.Clientes?.Remove(cliente);
                        context.SaveChanges(true);
                        TempData["msg"] = "<script>alert('El cliente fue borrado con éxito');</script>";
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Farmucho/Views/Cliente/Agregar.cshtml
@model Cliente
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Agregar Cliente</h1>
<hr />

<form asp-action="GuardarAgregar">
    <div class="form-group mb-3">
        <label class="control-label">NOMBRE</label>
        <input asp-for="Nombre" class="form-control" type="text" />
    </div>
    <div class="form-group mb-3">
        <label class="control-label">APELLIDO</label>
        <input asp-for="Apellido" class="form-control" type="text" />
    </div>
    <div class="form-group mb-3">
        <label class="control-label">TELEFONO</label>
        <input asp-for="Telefono" class="form-control type="tel" />
    </div>
    <div class="form-group mb-3">
        <label class="control-label">MAIL</label>
        <input asp-for="Mail" class="form-control" type="email" />
    </div>
    <div class="form-group mb-3">
        <label class="control-label">CUIT</label>
        <input asp-for="Cuit" class="form-control" type="number" />
    </div>
    <div class="form-group mb-3" style="margin-top:10px">

        <input type="submit" value="Enviar" class="btn btn-success" />

    </div>
</form>

<a asp-action="Index" asp-controller="Cliente" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>

Farmucho/Views/Cliente/Editar.cshtml
@model Cliente
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Editar Cliente</h1>
<hr />

<form asp-action="Update">
    <div class="form-group d-none">
        <label class="control-label">ID</label>
        <input asp-for="Id" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">NOMBRE</label>
        <input asp-for="Nombre" class="form-control" type="text" />
    </div>
    <div class="form-group">
        <label class="control-label">APELLIDO</label>
        <input asp-for="Apellido" class="form-control" type="text" />
    </div>
    <div class="form-group">
        <label class="control-label">TELEFONO</label>
        <input asp-for="Telefono" class="form-control" type="tel" />
    </div>
    <div class="form-group">
        <label class="control-label">MAIL</label>
        <input asp-for="Mail" class="form-control" type="email" />
    </div>
    <div class="form-group">
        <label class="control-label">CUIT</label>
        <input asp-for="Cuit" class="form-control" type="number" />
    </div>
    <div class="form-group" style="margin-top:10px">
        <input type="submit" value="Enviar" class="btn btn-success" />
    </div>
</form>

<a asp-action="Index" asp-controller="Cliente" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>

Farmucho/Views/Cliente/Index.cshtml
@model List<Cliente>
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Clientes</h1>
<hr />
<p>Se listarán todos los clientes registrados</p>

<a asp-action="Agregar" class="btn btn-success" style="margin-top:10px; margin-bottom:20px; float: right">Agregar Cliente</a>

<table class="table">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>APELLIDO</th>
            <th>TELEFONO</th>
            <th>MAIL</th>
            <th>CUIT</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <label>@item.Nombre</label>
            </td>
            <td>
                <label>@item.Apellido</label>
            </td>
            <td>
                <label>@item.Telefono</label>
            </td>
            <td>
                <label>@item.Mail</label>
            </td>
            <td>
                <label>@item.Cuit</label>
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.Id" class="iconito iconito-verde fa-sharp fa-solid fa-pen-to-square fa-lg"></a>
            </td>
            <td>
                <a asp-action="Borrar" asp-route-id="@item.Id" class="iconito iconito-rojo fa-sharp fa-solid fa-trash fa-lg"></a>
            </td>
        </tr>
    }
</table>