Farmucho/Models/Factura.cs
namespace Farmucho.Models
{
    public class Factura
    {
        public static int Id { get; set; }
        public Cliente? ClienteFac { get; set; }
        public List<ItemFactura> ItemsFactura { get; set; }
        public int NumFac { get; set; }
        public double ImporteTotal { get; set; }
        public Factura(Cliente cliente, List<ItemFactura> itemsFactura)
        {
            NumFac = ++Id;
            ClienteFac = cliente;
            ItemsFactura = itemsFactura;
            ImporteTotal += CalcularTotal();
        }
        public Factura(List<ItemFactura> itemsFactura)
        {
            Id++;
            NumFac = Id;
            ItemsFactura = itemsFactura;
            ImporteTotal += CalcularTotal();
        }
        public double CalcularTotal()
        {
            double total = 0;
            foreach (ItemFactura itemFactura in ItemsFactura)
            {
                total += itemFactura.Importe;
            }
            return total;
        }
    }
}

Farmucho/Controllers/FacturaController.cs
using Farmucho.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection.Metadata;

namespace Farmucho.Controllers
{
    public class FacturaController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(int cant)
        {
            if (cant > 0 && cant <= 30)
            {
                ViewModel.Prod = cant;
                return RedirectToAction("DatosFactura");
            }
            else
            {
                //TempData["msg"] = "<script>alert('La cantidad debe ser entre 1-30');</script>";
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult DatosFactura()
        {
            ViewModel viewModel = new();
            viewModel.CantProductos = new int[viewModel.Cant];
            viewModel.IdProductos = new int[viewModel.Cant];
            viewModel.ListaClientes?.Add(new() { Text = "Consumidor Final", Value = "-1" });
            viewModel.ListaMedicamentos?.Add(new() { Text = "Seleccione un producto", Value = "-1" });
            List<Cliente>? clientes = Lista.ListarClientes();
            List<Inventario>? inventarios = Lista.ListarInventario();
            if (clientes != null)
            {
                foreach (var c in clientes)
                {
                    viewModel.ListaClientes?.Add(new() { Text = c.Cuit.ToString(), Value = c.Id.ToString() });
                }
            }
            if (inventarios != null)
            {
                foreach (var m in inventarios)
                {
                    viewModel.ListaMedicamentos?.Add(new() { Text = m.Nombre, Value = m.Id.ToString() });
                }
            }
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult MostrarFactura(ViewModel vm)
        {
            Cliente? cliente = null;
            if (vm.IdCliente != -1)
            {
                cliente = Busqueda.BuscarCliente(vm.IdCliente);
            }

            List<ItemFactura> itemsFactura = new();
            for (int i = 0; i < vm.IdProductos?.Length; i++)
            {
                Inventario? medicamento = Busqueda.BuscarInventario(vm.IdProductos[i]);
                if (medicamento != null && vm.CantProductos?[i] > 0)
                {
                    itemsFactura.Add(new ItemFactura(medicamento, vm.CantProductos[i], medicamento.PrecioVenta));
                }
            }
            if (itemsFactura.Any() && cliente != null)
            {
                Factura factura = new(cliente, itemsFactura);
                return View(factura);
            }
            else if (itemsFactura.Any())
            {
                Factura factura = new(itemsFactura);
                return View(factura);
            }
            else
            {
                TempData["msg"] = "<script>alert('Ingrese al menos un producto, cantidad superior a 0');</script>";
                return RedirectToAction("DatosFactura");
            }
        }
    }
}

Farmucho/Views/Factura/DatosFactura.cshtml
@model ViewModel
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Factura</h1>
<hr />
<p>Simule una venta y genere una factura</p>

<form asp-action="MostrarFactura">
    <table class="table">
        <thead>
            <tr>
                <th>Cliente</th>
            </tr>
        </thead>
        <tr>
            <td>
                <select asp-for="IdCliente" class="form-control" asp-items="@Model.ListaClientes"></select>
            </td>
        </tr>
    </table>
    <table class="table">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        @for (int i = 0; i < Model.Cant; i++)
        {
            @if (Model.IdProductos?[i] != null && Model.CantProductos?[i] != null)
            {
                <tr>
                    <td>
                        <select asp-for="@Model.IdProductos[i]" class="form-control" asp-items="@Model.ListaMedicamentos"></select>
                    </td>
                    <td>
                        <input asp-for="@Model.CantProductos[i]" type="number" class="form-control" min="0" />
                    </td>
                </tr>
            }
        }
    </table>
    <div class="form-group" style="margin-top:10px">
        <input type="submit" value="Enviar" class="btn btn-outline-dark" />
    </div>
</form>

<a asp-action="Index" asp-controller="Factura" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>

Farmucho/Views/Factura/Index.cshtml
@*@Html.Raw(TempData["msg"])*@

<h1>Factura</h1>
<hr />
<p>Ingrese la cantidad de productos a facturar (maximo 30 productos)</p>

<form asp-action="Update">
    <div class="container">
        <div class="form-group mb-3">
            <label class="control-label"><b>CANTIDAD DE PRODUCTOS</b></label>
            <input type="number" name="cant" class="form-control" min="1" max="30" />
        </div>
        <div class="form-group mb-3">
            <input type="submit" value="AGREGAR" class="btn btn-secondary" />
        </div>
    </div>
</form>

Farmucho/Views/Factura/MostrarFactura.cshtml
@model Factura

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Factura #@Model.NumFac</h1>
<hr />

<h2>Datos del cliente</h2>

@if (@Model.ClienteFac != null)
{
    <table class="table">
        <thead>
            <tr>
                <th>NOMBRE</th>
                <th>APELLIDO</th>
                <th>CUIT/CUIL</th>
            </tr>
        </thead>
        <tr>
            <td>
                <label>@Model.ClienteFac.Nombre</label>
            </td>
            <td>
                <label>@Model.ClienteFac.Apellido</label>
            </td>
            <td>
                <label>@Model.ClienteFac.Cuit</label>
            </td>
        </tr>
    </table>
}
else
{
    <p><b>Consumidor Final</b></p>
}

<h2>Detalles del producto</h2>

<table class="table">
    <thead>
        <tr>
            <th>PRODUCTO</th>
            <th>DROGA</th>
            <th>LABORATORIO</th>
            <th>PRECIO UNITARIO</th>
            <th>CANTIDAD</th>
            <th>IMPORTE</th>
        </tr>
    </thead>
    @foreach (var i in Model.ItemsFactura)
    {
        <tr>
            <td>
                <label>@i.Medicamento?.Nombre</label>
            </td>
            <td>
                <label>@i.Medicamento?.Droga</label>
            </td>
            <td>
                <label>@i.Medicamento?.Laboratorio</label>
            </td>
            <td>
                <label>@i.Medicamento?.PrecioVenta</label>
            </td>
            <td>
                <label>@i.Cantidad</label>
            </td>
            <td>
                <label>@i.Importe</label>
            </td>
        </tr>
    }
</table>

<h3>Importe total</h3>
<p>$@Model.ImporteTotal</p>

<button class="btn btn-outline-dark fa fa-print" style="margin-top:10px; margin-bottom:10px" aria-hidden="true" onclick="window.print()"></button>

<a asp-action="DatosFactura" asp-controller="Factura" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>