Farmucho/Models/Inventario.cs
using System.ComponentModel.DataAnnotations;

namespace Farmucho.Models
{
    public class Inventario
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string? Nombre { get; set; }
        [Required]
        public int Cantidad { get; set; }
        [Required]
        public string? Droga { get; set; }
        [Required]
        public string? Vencimiento { get; set; }
        [Required]
        public string? Laboratorio { get; set; }
        [Required]
        public double PrecioCompra { get; set; }
        [Required]
        public double PrecioVenta { get; set; }
    }
}

Farmucho/Controllers/InventarioController.cs
using Microsoft.AspNetCore.Mvc;
using Farmucho.Models;
using System.Collections.Generic;

namespace Farmucho.Controllers
{
    public class InventarioController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(Lista.ListarInventario());
        }
        [HttpGet]
        public IActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GuardarAgregar(Inventario inventario)
        {
            if (ModelState.IsValid)
            {
                using (FarmaciaContext context = new())
                {
                    context.Inventario?.Add(inventario);
                    context.SaveChanges();
                }
                TempData["msg"] = "<script>alert('El medicamento fue agregado con éxito');</script>";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "<script>alert('Por favor, llene todos los campos');</script>";
                return View("Agregar");
            }
        }
        [HttpGet]
        public IActionResult Editar(int id)
        {
            using FarmaciaContext context = new();
            
                Inventario? inventario = context.Inventario?.Find(id);

                if (inventario != null)
                {
                    return View(inventario);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            
        }
        [HttpPost]
        public IActionResult Update(int id, Inventario inventario)
        {
            if (ModelState.IsValid)
            {
                using (FarmaciaContext context = new())
                {
                    if (id != inventario.Id)
                    {
                        return NotFound();
                    }
                    else
                    {
                        context.Inventario?.Update(inventario);
                        context.SaveChanges();
                        TempData["msg"] = "<script>alert('El medicamento fue editado con éxito');</script>";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "<script>alert('Por favor, llene todos los campos');</script>";
                return View("Editar");
            }
        }
        [HttpGet]
        public IActionResult Borrar(int id)
        {
            using (FarmaciaContext context = new())
            {
                if (id != 0)
                {
                    Inventario? inventario = context.Inventario?.Find(id);
                    if (inventario != null)
                    {
                        context.Inventario?.Remove(inventario);
                        context.SaveChanges(true);
                        TempData["msg"] = "<script>alert('El medicamento fue borrado con éxito');</script>";
                    }
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Farmucho/Views/Inventario/Agregar.cshtml
@model Inventario
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Agregar Medicamento</h1>
<hr />

<form asp-action="GuardarAgregar">
    <div class="form-group mb-3p">
        <label class="control-label">NOMBRE</label>
        <input asp-for="Nombre" class="form-control" type="text" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">CANTIDAD</label>
        <input asp-for="Cantidad" class="form-control" type="number" min="0" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">DROGA</label>
        <input asp-for="Droga" class="form-control" type="text" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">VENCIMIENTO</label>
        <input asp-for="Vencimiento" class="form-control" type="date" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">LABORATORIO</label>
        <input asp-for="Laboratorio" class="form-control" type="text" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">PRECIO COMPRA</label>
        <input asp-for="PrecioCompra" class="form-control" type="number" />
    </div>
    <div class="form-group mb-3p">
        <label class="control-label">PRECIO VENTA</label>
        <input asp-for="PrecioVenta" class="form-control" type="number" />
    </div>
    <div class="form-group mb-3p" style="margin-top:10px">
        <input type="submit" value="Enviar" class="btn btn-success" />
    </div>
</form>

<a asp-action="Index" asp-controller="Inventario" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>

Farmucho/Views/Inventario/Editar.cshtml
@model Inventario
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Editar Medicamento</h1>
<hr />

<form asp-action="Update">
    <div class="form-group d-none">
        <label class="control-label">ID</label>
        <input asp-for="Id" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">NOMBRE</label>
        <input asp-for="Nombre" class="form-control" type="text" />
    </div>
    <div class="form-group">
        <label class="control-label">CANTIDAD</label>
        <input asp-for="Cantidad" class="form-control" min="0" />
    </div>
    <div class="form-group">
        <label class="control-label">DROGA</label>
        <input asp-for="Droga" class="form-control" type="text" />
    </div>
    <div class="form-group">
        <label class="control-label">VENCIMIENTO</label>
        <input asp-for="Vencimiento" class="form-control" type="date" />
    </div>
    <div class="form-group">
        <label class="control-label">LABORATORIO</label>
        <input asp-for="Laboratorio" class="form-control" type="text" />
    </div>
    <div class="form-group">
        <label class="control-label">PRECIO COMPRA</label>
        <input asp-for="PrecioCompra" class="form-control" type="number" />
    </div>
    <div class="form-group">
        <label class="control-label">PRECIO VENTA</label>
        <input asp-for="PrecioVenta" class="form-control" type="number" />
    </div>
    <div class="form-group" style="margin-top:10px">
        <input type="submit" value="Enviar" class="btn btn-outline-dark" />
    </div>
</form>

<a asp-action="Index" asp-controller="Inventario" class="btn btn-outline-dark fa fa-arrow-left" style="margin-top:10px; margin-bottom:10px" aria-hidden="true"></a>

Farmucho/Views/Inventario/Index.cshtml
@model List<Inventario>
@Html.Raw(TempData["msg"])

<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />

<h1>Inventario</h1>
<hr />
<p>Se listarán todos los medicamentos registrados</p>

<a asp-action="Agregar" class="btn btn-success" style="margin-top:10px; margin-bottom:20px; float: right">Agregar Medicamento</a>

<table class="table">
    <thead>
        <tr>
            <th>NOMBRE</th>
            <th>CANTIDAD</th>
            <th>DROGA</th>
            <th>VENCIMIENTO</th>
            <th>LABORATORIO</th>
            <th>PRECIO DE COMPRA</th>
            <th>PRECIO DE VENTA</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                <label>@item.Nombre</label>
            </td>
            <td>
                <label>@item.Cantidad</label>
            </td>
            <td>
                <label>@item.Droga</label>
            </td>
            <td>
                <label>@item.Vencimiento</label>
            </td>
            <td>
                <label>@item.Laboratorio</label>
            </td>
            <td>
                <label>@item.PrecioCompra</label>
            </td>
            <td>
                <label>@item.PrecioVenta</label>
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.Id" class="iconito iconito-verde fa-sharp fa-solid fa-pen-to-square fa-lg"></a>
            </td>
            <td>
                <a asp-action="Borrar" asp-route-id="@item.Id" class="iconito iconito-rojo fa-sharp fa-solid fa-trash fa-lg"></a>
            </td>
        </tr>
    }
</table>